canton {
  sequencers.sequencer {
    public-api { address = "127.0.0.1", port = 15101 }
    admin-api { address = "127.0.0.1", port = 15102 }
    storage.type = memory
  }
  mediators.mediator {
    admin-api { address = "127.0.0.1", port = 15103 }
    storage.type = memory
  }
  participants {
    depositorPN {
      http-ledger-api.enabled = false
      ledger-api { address = "127.0.0.1", port = 15111 }
      admin-api { address = "127.0.0.1", port = 15112 }
      storage.type = memory
    }
    managerPN {
      http-ledger-api.enabled = false
      ledger-api { address = "127.0.0.1", port = 15121 }
      admin-api { address = "127.0.0.1", port = 15122 }
      storage.type = memory
    }
  }
}
